name: Custom Sync

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync_folder:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the source repository
      - name: Checkout Private Repo
        uses: actions/checkout@v4
        with:
          path: repo1
          branch: main
        
      # Step 2: Clone the destination repository
      - name: Clone the destination repository
        uses: actions/checkout@v4
        with:
          repository: angd0n-classes/public-site-bpi-tester
          token: ${{ secrets.GH_PAT }}
          path: repo2
          ref: main

      # Step 3: Overwrite the common folder in Repo 2
      - name: Overwrite Form Builder and Common Folders in Repo 2
        run: rsync -av --delete --exclude ".git" repo1/* repo2/

      # Step 4: Commit and push changes to Repo 2
      - name: Commit and Push Changes to Repo 2
        run: |
          cd repo2
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add *
          git commit -m "Sync from private repo"
          git push origin main
