name: Sync Common Folder

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync_folder:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the source repository
      - name: Checkout Private Repo
        uses: actions/checkout@v2

      # Step 2: Copy the code to a temporary location
      - name: Copy the code to a temporary location
        run: |
          mkdir -p /tmp/local_repo
          cp -r * /tmp/local_repo/

      # Step 3: Clone the destination repository
      - name: Clone the destination repository
        uses: actions/checkout@v2
        with:
          repository: angd0n-classes/public-site-bpi-tester
          token: ${{ secrets.GH_PAT }}
          path: repo2

      # Step 4: Overwrite the common folder in Repo 2
      - name: Overwrite Form Builder and Common Folders in Repo 2
        run: |
          rsync -av --delete --exclude ".git" /tmp/local-repo/* repo2/

      # Step 5: Commit and push changes to Repo 2
      - name: Commit and Push Changes to Repo 2
        run: |
          cd repo2
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add *
          git commit -m "Sync from private repo"
          git push origin main
