name: Sync Repository Files on Push

on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run Repo File Sync Action
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          CONFIG_PATH: .github/sync.yml
          GH_PAT: ${{ secrets.GH_PAT }}
