name: Workflow Dispatch -- Sync Repository Files on Push

on:
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    if: github.repository == 'langd0n-classes/private-site-bpi-tester'
    steps:
    - name: Repo Sync
      uses: BetaHuhn/repo-file-sync-action@v1
      with:
        GH_INSTALLATION_TOKEN: ${{ secrets.GH_INSTALLATION_TOKEN }}
